apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-test
  labels:
    app: dating-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dating-test
  template:
    metadata:
      labels:
        app: dating-test
    spec:
      containers:
      - name: dating-test
        imagePullPolicy: IfNotPresent
        image: oracionm/personal:1.0.7
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dating-test-service
spec:
  selector:
    app: dating-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dating-test-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: dating-test.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dating-test-service
            port:
              number: 80
